// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A habit suggestion AI agent.
 *
 * - getHabitSuggestion - A function that handles the habit suggestion process.
 * - HabitSuggestionInput - The input type for the getHabitSuggestion function.
 * - HabitSuggestionOutput - The return type for the getHabitSuggestion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const HabitSuggestionInputSchema = z.object({
  habitName: z.string().describe('The name of the habit.'),
  trackingData: z
    .string()
    .describe(
      'The tracking data for the habit, including completion dates and any notes.'
    ),
});
export type HabitSuggestionInput = z.infer<typeof HabitSuggestionInputSchema>;

const HabitSuggestionOutputSchema = z.object({
  suggestion: z
    .string()
    .describe(
      'A personalized suggestion for improving habit consistency based on the tracking data.'
    ),
});
export type HabitSuggestionOutput = z.infer<typeof HabitSuggestionOutputSchema>;

export async function getHabitSuggestion(
  input: HabitSuggestionInput
): Promise<HabitSuggestionOutput> {
  return habitSuggestionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'habitSuggestionPrompt',
  input: {schema: HabitSuggestionInputSchema},
  output: {schema: HabitSuggestionOutputSchema},
  prompt: `You are a habit improvement expert. Analyze the provided habit tracking data and provide a personalized suggestion for improving consistency.

Habit Name: {{{habitName}}}
Tracking Data: {{{trackingData}}}

Suggestion:`,
});

const habitSuggestionFlow = ai.defineFlow(
  {
    name: 'habitSuggestionFlow',
    inputSchema: HabitSuggestionInputSchema,
    outputSchema: HabitSuggestionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
