
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A habit suggestion AI agent.
 *
 * - getHabitSuggestion - A function that handles the habit suggestion process.
 * - HabitSuggestionInput - The input type for the getHabitSuggestion function.
 * - HabitSuggestionOutput - The return type for the getHabitSuggestion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const HabitSuggestionInputSchema = z.object({
  habitName: z.string().describe('The name of the habit.'),
  habitDescription: z.string().optional().describe('The description of the habit.'),
  daysOfWeek: z.array(z.string()).describe('Days of the week the habit is scheduled for (e.g., ["Mon", "Wed", "Fri"]).'),
  optimalTiming: z.string().optional().describe('The general optimal time of day suggested for the habit (e.g., morning, afternoon, evening).'),
  durationHours: z.number().optional().describe('The suggested duration in hours for the habit.'),
  durationMinutes: z.number().optional().describe('The suggested duration in minutes for the habit (0-59).'),
  specificTime: z.string().optional().describe('The specific time scheduled for the habit (HH:mm format, e.g., "08:00").'),
  trackingData: z
    .string()
    .describe(
      'The tracking data for the habit, including completion dates and any notes. Example: "Completions: 2023-10-25 at 08:05, 2023-10-26 at 08:00. Notes: Felt tired on 2023-10-25."'
    ),
});
export type HabitSuggestionInput = z.infer<typeof HabitSuggestionInputSchema>;

const HabitSuggestionOutputSchema = z.object({
  suggestion: z
    .string()
    .describe(
      'A personalized suggestion for improving habit consistency based on the tracking data and habit details.'
    ),
});
export type HabitSuggestionOutput = z.infer<typeof HabitSuggestionOutputSchema>;

export async function getHabitSuggestion(
  input: HabitSuggestionInput
): Promise<HabitSuggestionOutput> {
  return habitSuggestionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'habitSuggestionPrompt',
  input: {schema: HabitSuggestionInputSchema},
  output: {schema: HabitSuggestionOutputSchema},
  prompt: `You are an encouraging and insightful habit coach.
Your goal is to provide a personalized, actionable suggestion to help the user improve or maintain their habit: '{{habitName}}'.

Here's information about the habit:
- Name: {{habitName}}
{{#if habitDescription}}- Description: {{habitDescription}}{{/if}}
- Scheduled Days: {{#if daysOfWeek}}{{#each daysOfWeek}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}{{else}}Not specified{{/if}}
{{#if optimalTiming}}- Suggested Optimal Timing: {{optimalTiming}}{{/if}}
- Target Duration:{{#if durationHours}} {{durationHours}} hour(s){{/if}}{{#if durationMinutes}} {{durationMinutes}} minute(s){{/if}}{{#unless durationHours}}{{#unless durationMinutes}} Not specified{{/unless}}{{/unless}}
{{#if specificTime}}- Scheduled Time: {{specificTime}}{{else}} Not specified{{/if}}

Here's the user's tracking data for this habit:
{{{trackingData}}}

Based on ALL this information, provide ONE concise and actionable suggestion. Focus on:
- **Consistency Patterns**: If the tracking data shows missed days, especially on scheduled days, address it. For example, if consistency drops on certain days, you could say: "I notice completions for '{{habitName}}' are less frequent on [Observed Day/Pattern based on data]. Could you try [Specific Action related to that day/pattern, e.g., a shorter session, a different time, or preparing beforehand]?"
- **Time & Duration**:
    - If the habit has a duration (e.g., {{durationHours}}h{{durationMinutes}}m) and consistency is low, and the total duration is significant (e.g. >30 mins), suggest breaking it down: "For '{{habitName}}', which you've scheduled for {{#if durationHours}}{{durationHours}}h{{/if}}{{#if durationMinutes}}{{durationMinutes}}m{{/if}}, if it feels like a large block, have you considered splitting it into smaller, more manageable sessions?"
    - If a specific time ({{specificTime}}) is set and tracking data suggests it's often missed, suggest alternatives: "The scheduled time for '{{habitName}}' is {{specificTime}}. If that's proving challenging, perhaps try shifting it by 30 minutes, or consider if the {{optimalTiming}} part of your day offers more flexibility?"
- **General Productivity Tips (if relevant and not contradicting user data)**: For instance, if optimalTiming is 'morning' and it's a focus-based habit: "Many find dedicating focused time in the morning, say between 7-9 AM for habits like '{{habitName}}', can be very effective as mental energy is often highest then." Or if it's an evening habit for winding down: "An evening habit like '{{habitName}}' can be a great way to prepare for restful sleep. Consistency is key here."
- **Positive Reinforcement**: If tracking data shows good consistency on scheduled days: "You're doing great with '{{habitName}}'! Your consistency is really paying off. Keep up the momentum!" If it's a new habit with initial completions: "Excellent start on '{{habitName}}'! Building a new habit takes effort, and you're on the right track."

Make your suggestion practical, supportive, and directly related to the provided habit details and tracking data. If tracking data is sparse, provide a more general tip related to the habit's nature.
`,
});

const habitSuggestionFlow = ai.defineFlow(
  {
    name: 'habitSuggestionFlow',
    inputSchema: HabitSuggestionInputSchema,
    outputSchema: HabitSuggestionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

